### ISSUE TITLE
Ambiguous ERROR messages

### ISSUE THREAD

**Issue by cidrblock** [facebookincubator/FCR#3]
This may be a question and not necessary an issue.

I see this error message in the server output:

```ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<SSHConnection._run_task() done, defined at /Users/bthornto/github/FCR2/venv/lib/python3.6/site-packages/asyncssh/connection.py:366> exception=CancelledError()>
concurrent.futures._base.CancelledError
```

It doesn't seem to correlate directly to a device failure so I'm not sure what to think of it.  

Any clue what it may indicate?

**Comment by sursingh** [comment]
When do you get this error? I am guessing you get this when you try and stop the server. Looking at the related code, I don't think it is related to any device failure. But I will take a look and see how we can address this.

**Comment by cidrblock** [comment]
It seems to happen roughly half of the devices in a group of 1000.  Is it possible the SSH session doesn't disconnect properly from the far side?

**Comment by cidrblock** [comment]
A little more information on this, it only happens on MacOS.  On an ubuntu 16.04, only expected permission and connection errors are logged.  Closing this as ubuntu is the end game and the mac is only in use during dev.
